M48
; DRILL file {KiCad (6.0.7)} date Thu Nov 24 18:50:47 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-24T18:50:47+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.250
%
G90
G05
T1
X192.14Y-77.25
X199.34Y-77.25
T2
X135.0Y-74.0
X143.0Y-74.0
T3
X101.96Y-75.307
X101.96Y-99.507
X158.07Y-82.45
T4
X99.85Y-119.6
X210.05Y-119.7
X210.1Y-73.35
T5
X109.245Y-114.85
X120.675Y-114.85
T0
M30
