M48
; DRILL file {KiCad (6.0.7)} date Mon Oct 31 13:42:52 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-31T13:42:52+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,5,6,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.200
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T2C0.250
%
G90
G05
T1
X168.21Y-97.95
X185.09Y-94.91
X189.989Y-100.559
X192.85Y-100.04
T2
X179.81Y-100.55
T0
M30
